=== camitava0321/java-examples/XML/xmlSchemas/example.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stringtype">
  <xs:restriction base="xs:string"/>
</xs:simpleType>
<xs:simpleType name="booleantype">
  <xs:restriction base="xs:boolean"/>
</xs:simpleType>

<xs:simpleType name="inttype">
  <xs:restriction base="xs:positiveInteger"/>
</xs:simpleType>

<xs:simpleType name="dectype">
  <xs:restriction base="xs:decimal"/>
</xs:simpleType>

<xs:simpleType name="datetype">
  <xs:restriction base="xs:date">
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="orderidtype">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{6}"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="addresstype">
  <xs:sequence>
    <xs:element name="address1" type="stringtype"/>
    <xs:element name="address2" type="stringtype"/>
    <xs:element name="city" type="stringtype"/>
    <xs:element name="country" type="stringtype"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="accounttype">
  <xs:sequence>
    <xs:element name="accountid" type="inttype"/>
    <xs:element name="accountname" type="stringtype"/>
    <xs:element name="accountopendate" type="datetype"/>
    <xs:element name="balance" type="dectype"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="account">
  <xs:sequence>
    <xs:element name="account" type="accounttype"/>
  </xs:sequence>
</xs:complexType>
<xs:complexType name="customerstype">
  <xs:sequence>
    <xs:element name="customer" type="customertype"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="customertype">
  <xs:sequence>
    <xs:element name="highnetworth" type="booleantype"/>
    <xs:element name="customerid" type="inttype"/>
    <xs:element name="customername" type="stringtype"/>
    <xs:element name="customerdob" type="datetype"/>
    <xs:element name="customeraddress" type="addresstype" maxOccurs="1"/>
    <xs:element name="accounts" maxOccurs="unbounded" type="account"/>
  </xs:sequence>
  <xs:attribute name="orderid" type="orderidtype" use="required"/>
</xs:complexType>

<xs:element name="customers" type="customerstype"/>

</xs:schema>

=== camitava0321/java-examples/XML/xmlFiles/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xmlSchemas/example.xsd">
  <customer orderid="001">
    <highnetworth>true</highnetworth>
    <customerid>1</customerid>
    <customername>Amitava Chakraborty</customername>
    <customerdob>2001-01-01</customerdob>
    <customeraddress>
      <address1>address1</address1>
      <address2>address2</address2>
      <city>city</city>
      <country>country</country>
    </customeraddress>
    <accounts>
      <account>
        <accountid>1</accountid>
        <accountname>account name1</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
      <account>
        <accountid>2</accountid>
        <accountname>account name2</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
      <account>
        <accountid>3</accountid>
        <accountname>account name3</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
    </accounts>
  </customer>
  <customer orderid="001">
    <highnetworth>true</highnetworth>
    <customerid>002</customerid>
    <customername>Chayanika Chakraborty</customername>
    <customerdob>2001-01-01</customerdob>
    <customeraddress>
      <address1>address1</address1>
      <address2>address2</address2>
      <city>city</city>
      <country>country</country>
    </customeraddress>
    <accounts>
      <account>
        <accountid>21</accountid>
        <accountname>account name1</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
      <account>
        <accountid>22</accountid>
        <accountname>account name2</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
      <account>
        <accountid>23</accountid>
        <accountname>account name3</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
    </accounts>
  </customer>
  <customer orderid="001">
    <highnetworth>true</highnetworth>
    <customerid>1</customerid>
    <customername>Jayanta Ray</customername>
    <customerdob>2001-01-01</customerdob>
    <customeraddress>
      <address1>address1</address1>
      <address2>address2</address2>
      <city>city</city>
      <country>country</country>
    </customeraddress>
    <accounts>
      <account>
        <accountid>31</accountid>
        <accountname>account name1</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
    </accounts>
  </customer>
  <customer orderid="003">
    <highnetworth>true</highnetworth>
    <customerid>1</customerid>
    <customername>Zeenat Rehman</customername>
    <customerdob>2001-01-01</customerdob>
    <customeraddress>
      <address1>address1</address1>
      <address2>address2</address2>
      <city>city</city>
      <country>country</country>
    </customeraddress>
    <accounts>
      <account>
        <accountid>51</accountid>
        <accountname>account name1</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
      <account>
        <accountid>52</accountid>
        <accountname>account name2</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
    </accounts>
  </customer>
  <customer orderid="005">
    <highnetworth>true</highnetworth>
    <customerid>1</customerid>
    <customername>Lee Jones</customername>
    <customerdob>2001-01-01</customerdob>
    <customeraddress>
      <address1>address1</address1>
      <address2>address2</address2>
      <city>city</city>
      <country>country</country>
    </customeraddress>
    <accounts>
      <account>
        <accountid>81</accountid>
        <accountname>account name1</accountname>
        <accountopendate>2001-01-01</accountopendate>
        <balance>0.0</balance>
      </account>
    </accounts>
  </customer>
</customers>
