=== camitava0321/java-examples/XML/src/com/amc/xml/xml/tij_menu.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/1999/XMLSchema">
  <xsd:annotation>
    <xsd:documentation>
      TIJ Restaurant Menu Schema.
    </xsd:documentation>
  </xsd:annotation>
 
   <xsd:element name="restaurant" 
        type="restaurantType"/>
   
   <xsd:complexType name="restaurantType">
     <xsd:element name="name" type="xsd:string"/>
     <xsd:element name="address" type="addressType"/>
     <xsd:element name="phone" type="xsd:string"/>
     <xsd:element name="menu" type="menuType"/>
   </xsd:complexType>  
   
   <xsd:complexType name="menuType">
     <xsd:attribute name="desc" type="xsd:string"/>
     <xsd:element name="menugroup" 
          type="menugroupType" minOccurs="1"
          maxOccurs=”unbounded”/>
  </xsd:complexType>
 
   <xsd:complexType name="menugroupType">
     <xsd:element name="menuitem" minOccurs="1"
                  maxOccurs=”unbounded”>
         <xsd:complexType>
         <xsd:element name="name" type="xsd:string" 
              minOccurs="1"/>
         <xsd:element name="price" type="xsd:string" 
              minOccurs="0"/>
         <xsd:element name="description" 
              type="xsd:string" minOccurs="0"/>
      </xsd:complexType>         
    </xsd:element>
   </xsd:complexType>
</xsd:schema>

=== camitava0321/java-examples/XML/src/com/amc/xml/xml/tij_menu.xml
<?xml version='1.0'?>
<?xml:stylesheet type="text/xsl" href="tij_menu.xsl" ?>
<restaurant
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="tij_menu.xsd">
  <name>TIJ's Restaurant</name>
  <address>
    <addr1>108 Java Sapien Avenue</addr1>
    <city>Wayne</city>
    <state>PA</state>
    <country>USA</country>
  </address>
  <phone>610-687-1234</phone>
  <menu>
    <menugroup desc="Starters">
      <menuitem>
        <name>Nachos</name>
        <price>$7.25</price>
        <description>cheddar and monterey jack cheese, salsa, sour cream and guacamole.  add jalapenos or black olives $.50 each</description>
      </menuitem>
      <menuitem>
        <name>Portabello Mushroom Cap</name>
        <price>$8.75</price>
        <description>Stuffed with crabmeat, andouille sausage and smoked tomato sauce</description>
      </menuitem>
      <menuitem>
        <name>Chicken Wings</name>
        <price>$4.95</price>
        <description>A dozen chicken Wings with blue cheese sauce.  Two dozen for $8.75</description>
      </menuitem>
      <menuitem>
        <name>Quesadilla</name>
        <price>$6.25</price>
        <description>Chicken, black beans, guacamole, salsa, fresca and sour cream</description>
      </menuitem>
    </menugroup>
    <menugroup desc="Salads, Big Salads, and Soups">
      <menuitem>
        <name>House Salad</name>
        <price>$4.75/$8.00</price>
        <description>Small or large house salad with balsamic herbed vinaigrette</description>
      </menuitem>
      <menuitem>
        <name>Mesclun Salad</name>
        <price>$7.25/$13.50</price>
        <description>with marinated mushrooms, roasted peppers, artichokes, fresh mossarella and balsamic vinaigrette</description>
      </menuitem>
      <menuitem>
        <name>Grilled Chicken Salad</name>
        <price>$6.75/$11.25</price>
        <description>soy sesame marinade, mixed greens, red and green peoppers, carrots, red onion, crispy fried wontons and honey ginger dressing</description>
      </menuitem>
      <menuitem>
        <name>Chicken Soup of the Day</name>
        <price>$2.30/$3.95</price>
      </menuitem>
    </menugroup>
    <menugroup desc="Pizza">
      <menuitem>
        <name>Duck Confit Pizza</name>
        <price>$9.00</price>
        <description>with caramelized onion, fresh thyme and goat cheese</description>
      </menuitem>
      <menuitem>
        <name>The Salty Pizza</name>
        <price>$8.50</price>
        <description>with proscuitto, black olives cotija cheese, tomatoes and anchovies</description>
      </menuitem>
      <menuitem>
        <name>Traditional Pizza</name>
        <price>$7.50</price>
        <description>red sauce and mozzarella cheese</description>
      </menuitem>
      <menuitem>
        <name>Toppings</name>
        <price>$.50</price>
        <description>Pepperoni, Sausage, Chicken, Grilled Portabello, Roasted Peppers, Sun Dried Tomatoes, Roasted Garlic, Broccoli Rabe, Spinach, Shrimp, Proscuitto, Black Olives, Goat Cheese, Bacon, Roasted Veggies, Green Peppers, Onions, Mushrooms</description>
      </menuitem>
    </menugroup>
    <menugroup desc="Entrees">
      <menuitem>
        <name>Grilled Rib Eye Steak</name>
        <price>$18.00</price>
        <description>with buttermilk biscuits, vegetable of the day and button mushroom gravy</description>
      </menuitem>
      <menuitem>
        <name>Pork Tenderloin</name>
        <price>$16.00</price>
        <description>dry rubbed with swiss chard, maple whipped sweet potatoes and apple bourbon sauce</description>
      </menuitem>
      <menuitem>
        <name>Grilled Chicken</name>
        <price>$16.00</price>
        <description>with mushroom risotto pesto sauce and tomato salsa</description>
      </menuitem>
      <menuitem>
        <name>Center Cut Sirlion</name>
        <price>$16.00</price>
        <description>with cheddar cheese mashed potatoes, horseradish sour cream and vegetable of the day</description>
      </menuitem>
    </menugroup>
    <menugroup desc="Kids">
      <menuitem>
        <name>Hot Dog</name>
        <price>$3.50</price>
        <description>on roll; with American Chees $3.75</description>
      </menuitem>
      <menuitem>
        <name>Grilled Cheese Sandwich</name>
        <price>$3.25</price>
        <description>The classic!</description>
      </menuitem>
      <menuitem>
        <name>Chicken Fingers</name>
        <price>$5.00</price>
        <description>Finger licking good</description>
      </menuitem>
    </menugroup>
    <menugroup desc="Beverages">
      <menuitem>
        <name>Milkshake</name>
        <price>$3.50</price>
        <description>vanilla, chocolate or strawberry; double thick, $5.00</description>
      </menuitem>
      <menuitem>
        <name>Orange Cream Soda Float</name>
        <price>$5.00</price>
      </menuitem>
      <menuitem>
        <name>Chocolate Milk</name>
        <price>$2.50</price>
      </menuitem>
    </menugroup>
  </menu>
</restaurant>
